version: '3'

services:
  db:
    container_name: libraryDB
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: libraryDB
    volumes:
      - ./postgres:/var/lib/postgresql/data

  db-admin:
    container_name: libraryDBAdmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: SecretPass123
